import {
  imageFiles,
  ATTACK_BLOCKS,
  ENEMY_SPEED,
} from '../gameSettings/settings';

const levelData = {
  level1: {
    background: imageFiles.galaxy1,
    sequences: [
      // block 1 (streamdown single)
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNSINGLE660,
        score: 10,
        lives: 1,
        speed: ENEMY_SPEED.medium,
        delayBefore: 1000,
      },
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNSINGLE420,
        score: 10,
        lives: 1,
        speed: ENEMY_SPEED.medium,
        delayBefore: 1000,
      },
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNSINGLE780,
        score: 10,
        lives: 1,
        speed: ENEMY_SPEED.medium,
        delayBefore: 1000,
      },
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNSINGLE1140,
        score: 10,
        lives: 1,
        speed: ENEMY_SPEED.medium,
        delayBefore: 1000,
      },
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNSINGLE60,
        score: 10,
        lives: 1,
        speed: ENEMY_SPEED.medium,
        delayBefore: 1000,
      },
      // block 2 (streamdown single in  rows)
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[0],
        number: 3,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNSINGLE660,
        score: 10,
        lives: 1,
        speed: ENEMY_SPEED.medium,
        delayBefore: 1000,
      },
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[0],
        number: 5,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNSINGLE420,
        score: 10,
        lives: 1,
        speed: ENEMY_SPEED.medium,
        delayBefore: 1000,
      },
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[0],
        number: 3,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNSINGLE780,
        score: 10,
        lives: 1,
        speed: ENEMY_SPEED.medium,
        delayBefore: 1000,
      },
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[0],
        number: 5,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNSINGLE1140,
        score: 10,
        lives: 1,
        speed: ENEMY_SPEED.medium,
        delayBefore: 1000,
      },
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[0],
        number: 3,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNSINGLE60,
        score: 10,
        lives: 1,
        speed: ENEMY_SPEED.medium,
        delayBefore: 1000,
      },
      // block 3 (streamdown in groups)
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNLEFT,
        score: 10,
        lives: 1,
        speed: ENEMY_SPEED.medium,
        delayBefore: 1000,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNRIGTH,
        score: 10,
        lives: 1,
        speed: ENEMY_SPEED.medium,
        delayBefore: 1000,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNLEFT,
        score: 10,
        lives: 1,
        speed: ENEMY_SPEED.medium,
        delayBefore: 1000,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNRIGTH,
        score: 10,
        lives: 1,
        speed: ENEMY_SPEED.medium,
        delayBefore: 1000,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNFULL,
        score: 10,
        lives: 1,
        speed: ENEMY_SPEED.medium,
        delayBefore: 1000,
      },
      // block 4 (streamdown in groups, last group reversed)
      {
        delayBetween: 500,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNLEFT,
        score: 10,
        lives: 1,
        speed: ENEMY_SPEED.medium,
        delayBefore: 500,
      },
      {
        delayBetween: 500,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNRIGTH,
        score: 10,
        lives: 1,
        speed: ENEMY_SPEED.medium,
        delayBefore: 500,
      },
      {
        delayBetween: 500,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNLEFT,
        score: 10,
        lives: 1,
        speed: ENEMY_SPEED.medium,
        delayBefore: 500,
      },
      {
        delayBetween: 500,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNRIGTH,
        score: 10,
        lives: 1,
        speed: ENEMY_SPEED.medium,
        delayBefore: 500,
      },
      {
        delayBetween: 500,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNFULLREVERSED,
        score: 10,
        lives: 1,
        speed: ENEMY_SPEED.medium,
        delayBefore: 500,
      },
      // block 5 (streamdown in groups with rows, last group reversed)
      {
        delayBetween: 500,
        imageEnemy: imageFiles.enemy[0],
        number: 5,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNLEFT,
        score: 10,
        lives: 1,
        speed: ENEMY_SPEED.medium,
        delayBefore: 500,
      },
      {
        delayBetween: 500,
        imageEnemy: imageFiles.enemy[0],
        number: 5,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNRIGTH,
        score: 10,
        lives: 1,
        speed: ENEMY_SPEED.medium,
        delayBefore: 500,
      },
      {
        delayBetween: 500,
        imageEnemy: imageFiles.enemy[0],
        number: 5,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNLEFT,
        score: 10,
        lives: 1,
        speed: ENEMY_SPEED.medium,
        delayBefore: 500,
      },
      {
        delayBetween: 500,
        imageEnemy: imageFiles.enemy[0],
        number: 5,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNRIGTH,
        score: 10,
        lives: 1,
        speed: ENEMY_SPEED.medium,
        delayBefore: 500,
      },
      {
        delayBetween: 500,
        imageEnemy: imageFiles.enemy[0],
        number: 5,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNFULLREVERSED,
        score: 10,
        lives: 1,
        speed: ENEMY_SPEED.fast,
        delayBefore: 500,
      },
      // block 6 (asteroids)
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[4],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNSINGLE660,
        score: 5,
        lives: 1,
        speed: ENEMY_SPEED.asteroid,
        delayBefore: 1000,
      },
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[4],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNSINGLE660,
        score: 5,
        lives: 1,
        speed: ENEMY_SPEED.asteroid,
        delayBefore: 1000,
      },
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[4],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNSINGLE420,
        score: 5,
        lives: 1,
        speed: ENEMY_SPEED.asteroid,
        delayBefore: 1000,
      },
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[4],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNSINGLE60,
        score: 5,
        lives: 1,
        speed: ENEMY_SPEED.asteroid,
        delayBefore: 1000,
      },
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[4],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNSINGLE1020,
        score: 5,
        lives: 1,
        speed: ENEMY_SPEED.asteroid,
        delayBefore: 1000,
      },
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[4],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNSINGLE1020,
        score: 5,
        lives: 1,
        speed: ENEMY_SPEED.asteroid,
        delayBefore: 1000,
      },
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[4],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNSINGLE60,
        score: 5,
        lives: 1,
        speed: ENEMY_SPEED.asteroid,
        delayBefore: 1000,
      },
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[4],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNLEFT,
        score: 5,
        lives: 1,
        speed: ENEMY_SPEED.asteroid,
        delayBefore: 1000,
      },
      // block 7 (streamdown single in  rows fast speed more lives)
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[1],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNSINGLE660,
        score: 15,
        lives: 3,
        speed: ENEMY_SPEED.medium,
        delayBefore: 1000,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[1],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNSINGLE420,
        score: 15,
        lives: 3,
        speed: ENEMY_SPEED.medium,
        delayBefore: 1000,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[1],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNSINGLE780,
        score: 15,
        lives: 3,
        speed: ENEMY_SPEED.medium,
        delayBefore: 1000,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[1],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNSINGLE1140,
        score: 15,
        lives: 3,
        speed: ENEMY_SPEED.medium,
        delayBefore: 1000,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[1],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNSINGLE60,
        score: 15,
        lives: 3,
        speed: ENEMY_SPEED.medium,
        delayBefore: 1000,
      },
      // block 8 (streamreturnmixed mixed  speed)
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNRIGHTMIXEDLEFT,
        score: 15,
        lives: 1,
        speed: ENEMY_SPEED.fast,
        delayBefore: 1000,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMUPMIXED,
        score: 15,
        lives: 1,
        speed: ENEMY_SPEED.fast,
        delayBefore: 1000,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNRIGHTMIXEDLEFT,
        score: 15,
        lives: 1,
        speed: ENEMY_SPEED.fast,
        delayBefore: 1000,
      },
      // block 9 (big ships and side assaults)
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[3],
        number: 1,
        attackBlock: ATTACK_BLOCKS.BADDIETYPE2,
        score: 150,
        lives: 8,
        speed: ENEMY_SPEED.slow,
        delayBefore: 1000,
      },
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[0],
        number: 2,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT1,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.fast,
        delayBefore: 1000,
      },
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[0],
        number: 3,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT3,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.fast,
        delayBefore: 1000,
      },
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT2,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.slow,
        delayBefore: 1000,
      },
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[0],
        number: 4,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT4,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.fast,
        delayBefore: 1000,
      },
      // block 10 (asteroids again)
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[4],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNSINGLE660,
        score: 5,
        lives: 1,
        speed: ENEMY_SPEED.asteroid,
        delayBefore: 1000,
      },
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[4],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNSINGLE660,
        score: 5,
        lives: 1,
        speed: ENEMY_SPEED.asteroid,
        delayBefore: 1000,
      },
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[4],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNSINGLE420,
        score: 5,
        lives: 1,
        speed: ENEMY_SPEED.asteroid,
        delayBefore: 1000,
      },
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[4],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNSINGLE60,
        score: 5,
        lives: 1,
        speed: ENEMY_SPEED.asteroid,
        delayBefore: 1000,
      },
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[4],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNSINGLE1020,
        score: 5,
        lives: 1,
        speed: ENEMY_SPEED.asteroid,
        delayBefore: 1000,
      },
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[4],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNSINGLE1020,
        score: 5,
        lives: 1,
        speed: ENEMY_SPEED.asteroid,
        delayBefore: 1000,
      },
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[4],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNSINGLE60,
        score: 5,
        lives: 1,
        speed: ENEMY_SPEED.asteroid,
        delayBefore: 1000,
      },
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[4],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNLEFT,
        score: 5,
        lives: 1,
        speed: ENEMY_SPEED.asteroid,
        delayBefore: 1000,
      },
      // block 11 (heavy ships mixed with fast sideassaults and streamdowns)
      // heavy
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[3],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNSINGLE660,
        score: 150,
        lives: 5,
        speed: ENEMY_SPEED.slow,
        delayBefore: 1000,
      },
      // streamdowns
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[2],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNLEFTMIXED,
        score: 80,
        lives: 3,
        speed: ENEMY_SPEED.medium,
        delayBefore: 1000,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[2],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNFULL,
        score: 80,
        lives: 3,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 1000,
      },
      // sideassault
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT4,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 500,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT3,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 500,
      },
      // heavy
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[3],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNSINGLE1140,
        score: 150,
        lives: 5,
        speed: ENEMY_SPEED.slow,
        delayBefore: 5000,
      },
      // sideassault
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT4,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 100,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT3,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 1000,
      },
      // streamdowns
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[2],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNLEFTMIXED,
        score: 80,
        lives: 3,
        speed: ENEMY_SPEED.medium,
        delayBefore: 1000,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[2],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNFULL,
        score: 80,
        lives: 3,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 1000,
      },
      // heavy
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[3],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNSINGLE60,
        score: 150,
        lives: 5,
        speed: ENEMY_SPEED.slow,
        delayBefore: 5000,
      },
      // sideassault
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT4,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 100,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT3,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 1000,
      },
      // streamdowns
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[2],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNLEFTMIXED,
        score: 80,
        lives: 3,
        speed: ENEMY_SPEED.medium,
        delayBefore: 1000,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[2],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNFULL,
        score: 80,
        lives: 3,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 1000,
      },
      // block 12 (final round)
      // heavy
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[3],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNFULL,
        score: 150,
        lives: 5,
        speed: ENEMY_SPEED.slow,
        delayBefore: 500,
      },
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[3],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNFULLREVERSED,
        score: 150,
        lives: 5,
        speed: ENEMY_SPEED.slow,
        delayBefore: 500,
      },
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[3],
        number: 2,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNFULL,
        score: 150,
        lives: 5,
        speed: ENEMY_SPEED.slow,
        delayBefore: 500,
      },
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[3],
        number: 2,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNFULLREVERSED,
        score: 150,
        lives: 5,
        speed: ENEMY_SPEED.slow,
        delayBefore: 500,
      },
      // sideassault
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT1,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 100,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT3,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 1000,
      },
      // sideassault
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT2,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 100,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT4,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 1000,
      },
      // sideassault
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT2,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 100,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT1,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 1000,
      },
      // sideassault
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT4,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 100,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT1,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 1000,
      },
      // asteroids
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[4],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNSINGLE660,
        score: 5,
        lives: 1,
        speed: ENEMY_SPEED.asteroid,
        delayBefore: 1000,
      },
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[4],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNSINGLE660,
        score: 5,
        lives: 1,
        speed: ENEMY_SPEED.asteroid,
        delayBefore: 1000,
      },
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[4],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNSINGLE420,
        score: 5,
        lives: 1,
        speed: ENEMY_SPEED.asteroid,
        delayBefore: 1000,
      },
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[4],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNSINGLE60,
        score: 5,
        lives: 1,
        speed: ENEMY_SPEED.asteroid,
        delayBefore: 1000,
      },
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[4],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNSINGLE1020,
        score: 5,
        lives: 1,
        speed: ENEMY_SPEED.asteroid,
        delayBefore: 1000,
      },
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[4],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNSINGLE1020,
        score: 5,
        lives: 1,
        speed: ENEMY_SPEED.asteroid,
        delayBefore: 1000,
      },
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[4],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNSINGLE60,
        score: 5,
        lives: 1,
        speed: ENEMY_SPEED.asteroid,
        delayBefore: 1000,
      },
      {
        delayBetween: 1000,
        imageEnemy: imageFiles.enemy[4],
        number: 1,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNLEFT,
        score: 5,
        lives: 1,
        speed: ENEMY_SPEED.asteroid,
        delayBefore: 1000,
      },
      // heavy
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[3],
        number: 3,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNFULL,
        score: 150,
        lives: 5,
        speed: ENEMY_SPEED.slow,
        delayBefore: 500,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[3],
        number: 3,
        attackBlock: ATTACK_BLOCKS.STREAMDOWNFULLREVERSED,
        score: 150,
        lives: 5,
        speed: ENEMY_SPEED.slow,
        delayBefore: 500,
      },
      // sideassault
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT1,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 100,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT3,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 1000,
      },
      // sideassault
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT2,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 100,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT4,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 1000,
      },
      // sideassault
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT2,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 100,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT1,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 1000,
      },
      // sideassault
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT4,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 100,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT1,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 1000,
      },
      // sideassault
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT1,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 100,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT3,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 1000,
      },
      // sideassault
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT2,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 100,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT4,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 1000,
      },
      // sideassault
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT2,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 100,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT1,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 1000,
      },
      // sideassault
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT4,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 100,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT1,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 1000,
      },
      // sideassault
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT1,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 100,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT3,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 1000,
      },
      // sideassault
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT2,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 100,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT4,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 1000,
      },
      // sideassault
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT2,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 100,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT1,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 1000,
      },
      // sideassault
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT4,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 100,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT1,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 1000,
      },
      // sideassault
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT1,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 100,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT3,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 1000,
      },
      // sideassault
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT2,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 100,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT4,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 1000,
      },
      // sideassault
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT2,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 100,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT1,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 1000,
      },
      // sideassault
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT4,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 100,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT1,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 1000,
      },
      // sideassault
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT1,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 100,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT3,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 1000,
      },
      // sideassault
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT2,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 100,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT4,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 1000,
      },
      // sideassault
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT2,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 100,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT1,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 1000,
      },
      // sideassault
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT4,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 100,
      },
      {
        delayBetween: 600,
        imageEnemy: imageFiles.enemy[0],
        number: 1,
        attackBlock: ATTACK_BLOCKS.SIDEASSAULT1,
        score: 70,
        lives: 2,
        speed: ENEMY_SPEED.veryfast,
        delayBefore: 1000,
      },
    ],
  },
};

export default levelData;
